# stage 1: build the application
FROM node:20.19.5-alpine3.21 AS build
WORKDIR /opt/server
COPY package.json .
COPY *.js . 
# this may add extra cache memory
RUN npm install
# stage 2: create the final image
FROM node:20.19.5-alpine3.21
# create the group and user
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && \
    chown -R roboshop:roboshop /opt/server
EXPOSE 8080
LABEL com.project="RoboShop" \
      author="Saikumar19" \
      component="cart"
ENV REDIS_HOST = "redis" \
    CATALOGUE_HOST = "catalogue" \
    CATALOGUE_PORT = "8080" 
USER roboshop
COPY --from=build --chown=roboshop:roboshop /opt/server /opt/server
CMD ["server.js" ]   
ENTRYPOINT ["node"]
   