# Stage 1: Build the application
FROM node:20.19.5-alpine3.21 AS build
WORKDIR /opt/server
COPY package.json .
COPY *.js .
# this may add extra cache memory
RUN npm install
# Stage 2: Create the final image
FROM node:20.19.5-alpine3.21
# create the group and user 
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && \
    chown -R roboshop:roboshop /opt/server
EXPOSE 8080
LABEL com.project="RoboShop" \
      com.author="Saikumar19" \
      component="user"
ENV MONGO="true" \
    REDIS_URL="redis://redis:6379" \
    MONGO_URL="mongodb://mongodb:27017/users" 
USER roboshop
COPY --from=build --chown=roboshop:roboshop /opt/server /opt/server
CMD ["server.js" ]   
ENTRYPOINT ["node"]
