FROM nginx:1.27-alpine

# Create non-root user and group
RUN addgroup -S nginxgroup && adduser -S nginxuser -G nginxgroup

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf
COPY static /usr/share/nginx/html


# Fix permissions
RUN chown -R nginxuser:nginxgroup /var/cache/nginx \
    && chown -R nginxuser:nginxgroup /var/run \
    && chown -R nginxuser:nginxgroup /usr/share/nginx/html \
    && chmod -R 755 /var/cache/nginx

# Switch to non-root user
USER nginxuser

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]