# FROM python:3.9 AS build
# WORKDIR /opt/server
# COPY payment.ini *.py requirements.txt ./
# RUN pip3 install  requirements.txt -r --prefix=/install

# FROM python:3.9-alpine3.21
# WORKDIR /opt/server
# RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && 
# COPY from --build  /install /usr/local/bin/

# ENV CART_HOST ="cart" \
#     CART_PORT ="8080" \
#     USER_HOST ="user" \
#     USER_PORT ="8080" \
#     AMQP_HOST ="rabbitmq"
# CMD ["uwsgi", "--ini", "payment.ini"]

FROM python:3.9
WORKDIR /opt/server
EXPOSE 8080
COPY payment.ini .
COPY payment.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt
ENV CART_HOST="cart" \
    CART_PORT="8080" \
    USER_HOST="user" \
    USER_PORT="8080" \
    AMQP_HOST="rabbitmq"
CMD ["uwsgi", "--ini", "payment.ini"]




