FROM maven:3.9.11
WORKDIR /opt/server
COPY pom.xml .
COPY src ./src
RUN mvn clean package
ENV CART_ENDPOINTS_HOST="cart:8080" \
    DB_HOST="mysql" 
CMD ["java", "-jar", "target/shipping-1.0.jar"]


   